# Generated by Django 4.2.1 on 2023-05-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_lecturer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_student',
        ),
    ]
