# Generated by Django 4.2.1 on 2023-05-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_lecturer_student_alter_user_is_lecturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_year', models.CharField(max_length=10)),
                ('department_name', models.CharField(max_length=30)),
                ('course_id', models.CharField(max_length=10)),
                ('course_name', models.TextField()),
                ('theoretical_hour', models.IntegerField()),
                ('practical_hour', models.IntegerField()),
                ('branch', models.CharField(max_length=20)),
                ('credit', models.IntegerField()),
                ('akts', models.IntegerField()),
                ('course_type', models.CharField(max_length=10)),
                ('is_course_chosen', models.BooleanField(default=False)),
                ('students', models.ManyToManyField(related_name='courses', to='account.student')),
            ],
        ),
    ]
