# Generated by Django 4.2.1 on 2023-05-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='courses',
            field=models.ManyToManyField(to='account.course'),
        ),
    ]
