# Generated by Django 4.2.1 on 2023-05-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_lecturer_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='courses',
            field=models.ManyToManyField(related_name='lecturers', to='account.course'),
        ),
    ]
