# Generated by Django 4.2.1 on 2023-05-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_lecturer_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='courses',
        ),
    ]
