# Generated by Django 4.2.1 on 2023-05-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_lecturer_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='courses',
            field=models.ManyToManyField(related_name='lecturers', to='account.course'),
        ),
    ]
